orbs:
  node: circleci/node@2.0.2

version: 2.1

workflows:
  jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: env?
            when: on_fail
            command: |
                    echo $XM_URL
         - xmatters/notify:
            author: "Jo mama"
            project: "that one project"
         - run: echo "Fin"